- recipes/tez.rb
Use hops_hdfs_directory resource instead of HDFS client directly from the recipe
> Use hops_hdfs_directory resource in tez recipe

- templates/default/hive-site.xml.erb
Testing it, don't merge it yet.
> Add superuser property in hive-site

- templates/default/hive-site.xml.erb
Tests here: https://github.com/hopshadoop/hops-testing/pull/11
> Use default values for restricted/hidden properties settings

- recipes/llap.rb
- recipes/metastore.rb
- recipes/server2.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-555
> [HOPSWORKS-555] restart on upgrade

- templates/default/start-hivecleaner.sh.erb
- templates/default/wiper.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-623
> [HOPSWORKS-623]  Sanitize Bash scripts

- recipes/cleaner.rb
- recipes/metastore.rb
- recipes/server2.rb
- templates/default/hivecleaner.service.erb
- templates/default/hivemetastore.service.erb
- templates/default/hiveserver2.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1091
> [HOPSWORKS-1091] Add Systemd unit file deps

- .gitignore
- attributes/default.rb
- metadata.rb
- recipes/install.rb
- templates/default/hive-site.xml.erb
- Install hudie bundle to /lib in hive installation
> [HOPSWORKS-34] Hudi for unified Stream/Batch processing

- recipes/metastore.rb
- recipes/server2.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1331
> [HOPSWORKS-1331] Consistent flag for system upgrades

- attributes/default.rb
- templates/default/hive-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1425
> [HOPSWORKS-1425] change hdfs prefix to hopsfs

- Berksfile
- attributes/default.rb
- metadata.rb
- recipes/_configure.rb
- recipes/install.rb
- recipes/metastore.rb
- recipes/server2.rb
- templates/default/consul/hive-service-health.sh.erb
- templates/default/consul/hiveserver2-consul.hcl.erb
- templates/default/consul/metastore-consul.hcl.erb
- templates/default/hive-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405
> [HOPSWORKS-1405] Register Hive services with Consul

- Berksfile
- metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1679
> [HOPSWORKS-1679] Pin deps

- templates/default/consul/hiveserver2-consul.hcl.erb
- templates/default/consul/metastore-consul.hcl.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1718
> [HOPSWORKS-1718] Register services with passing health state

- attributes/default.rb
- metadata.rb
- recipes/_configure.rb
- recipes/db.rb
- recipes/install.rb
- recipes/llap.rb
- recipes/metastore.rb
- recipes/server2.rb
- recipes/tez.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1694
> [HOPSWORKS-1694] run user code in docker

- recipes/_configure.rb
- recipes/db.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1825
> [HOPSWORKS-1825] Connect to local mysqld

- attributes/default.rb
- metadata.rb
- recipes/_configure.rb
- recipes/install.rb
- recipes/metastore.rb
- recipes/server2.rb
- templates/default/hive-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
> [HOPSWORKS-1657] System users x.509 v2

- recipes/metastore.rb
- recipes/server2.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1977
> [HOPSWORKS-1977] Replace kagent/test with kagent/enabled

- recipes/metastore.rb
- recipes/server2.rb
- templates/default/hivemetastore.service.erb
- templates/default/hiveserver2.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1933
> [HOPSWORKS-1933] do not hang if consul not started

- recipes/metastore.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2053
> [HOPSWORKS-2053] Add NameNode to metastore systemd unit dependencies

- templates/default/hivemetastore.service.erb
- templates/default/hiveserver2.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units

- templates/default/hivemetastore.service.erb
- templates/default/hiveserver2.service.erb
* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Wait before each restart
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units (#72)

- templates/default/hivemetastore.service.erb
- templates/default/hiveserver2.service.erb
fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2292
> [HOPSWORKS-2292] remove systemd waiting mechanism

- attributes/default.rb
- recipes/_configure.rb
- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
> [HOPSWORKS-2578] Move Hive logs under data volume

- attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2939
> [HOPSWORKS-2939] Bump up Tez version

- attributes/default.rb
Realted to https://github.com/logicalclocks/hudi/pull/18
> bump hudi version to 0.10.0.2

- attributes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-318
> [CLOUD-318] update version of hive

- templates/default/hive-env.sh.erb
> Prepare for 3.1.1 release
